---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: rancher/dind:v0.3.0
  commands:
  - ENABLE_DOCKER=true ./scripts/ci
  privileged: true

- name: latest
  pull: default
  image: rancher/dind:v0.3.0
  commands:
  - ENABLE_DOCKER=true UPLOAD_LATEST=true ./scripts/ci
  privileged: true
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
